
package sipo.cpic.efs.services;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetFileWS", targetNamespace = "http://sipo/cpic/efs/services")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetFileWS {


    /**
     * 
     * @param fid
     * @param version
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetrieveFile")
    @WebResult(targetNamespace = "http://sipo/cpic/efs/services")
    @RequestWrapper(localName = "RetrieveFile", targetNamespace = "http://sipo/cpic/efs/services", className = "sipo.cpic.efs.services.RetrieveFile")
    @ResponseWrapper(localName = "RetrieveFileResponse", targetNamespace = "http://sipo/cpic/efs/services", className = "sipo.cpic.efs.services.RetrieveFileResponse")
    public String retrieveFile(
            @WebParam(name = "Fid", targetNamespace = "http://sipo/cpic/efs/services")
                    String fid,
            @WebParam(name = "version", targetNamespace = "http://sipo/cpic/efs/services")
                    String version);

    /**
     * 
     * @param fid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "RetrieveFileMax")
    @WebResult(targetNamespace = "http://sipo/cpic/efs/services")
    @RequestWrapper(localName = "RetrieveFileMax", targetNamespace = "http://sipo/cpic/efs/services", className = "sipo.cpic.efs.services.RetrieveFileMax")
    @ResponseWrapper(localName = "RetrieveFileMaxResponse", targetNamespace = "http://sipo/cpic/efs/services", className = "sipo.cpic.efs.services.RetrieveFileMaxResponse")
    public String retrieveFileMax(
            @WebParam(name = "Fid", targetNamespace = "http://sipo/cpic/efs/services")
                    String fid);

}
