
package sipo.cpic.efs.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetFileWSService", targetNamespace = "http://sipo/cpic/efs/services", wsdlLocation = "http://10.1.10.112:7001/GetFileWSN/GetFileWSN?WSDL")
public class GetFileWSService
    extends Service
{

    private final static URL GETFILEWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException GETFILEWSSERVICE_EXCEPTION;
    private final static QName GETFILEWSSERVICE_QNAME = new QName("http://sipo/cpic/efs/services", "GetFileWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.1.10.112:7001/GetFileWSN/GetFileWSN?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GETFILEWSSERVICE_WSDL_LOCATION = url;
        GETFILEWSSERVICE_EXCEPTION = e;
    }

    public GetFileWSService() {
        super(__getWsdlLocation(), GETFILEWSSERVICE_QNAME);
    }

    public GetFileWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETFILEWSSERVICE_QNAME, features);
    }

    public GetFileWSService(URL wsdlLocation) {
        super(wsdlLocation, GETFILEWSSERVICE_QNAME);
    }

    public GetFileWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETFILEWSSERVICE_QNAME, features);
    }

    public GetFileWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetFileWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetFileWS
     */
    @WebEndpoint(name = "GetFileWSSoapPort")
    public GetFileWS getGetFileWSSoapPort() {
        return super.getPort(new QName("http://sipo/cpic/efs/services", "GetFileWSSoapPort"), GetFileWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetFileWS
     */
    @WebEndpoint(name = "GetFileWSSoapPort")
    public GetFileWS getGetFileWSSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://sipo/cpic/efs/services", "GetFileWSSoapPort"), GetFileWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETFILEWSSERVICE_EXCEPTION!= null) {
            throw GETFILEWSSERVICE_EXCEPTION;
        }
        return GETFILEWSSERVICE_WSDL_LOCATION;
    }

}
