server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://localhost:13306/localweb?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
mybatis:
  #MyBatis扫描
  mapper-locations: classpath*:mapper/*.xml
  #起别名。可省略写mybatis的xml中的resultType的全路径
  type-aliases-package: com.example.sbootdemo.domain
